name: Update README with Commit Count

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # Fazer checkout do repositório
    - name: Check out the repository
      uses: actions/checkout@v2

    # Configurar Node.js para rodar o script
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Instalar dependências necessárias
    - name: Install dependencies
      run: npm install node-fetch

    # Rodar o script para contar commits e atualizar o README.md
    - name: Count Commits and Update README
      run: |
        const fetch = require('node-fetch');
        const fs = require('fs');
        const token = process.env.GITHUB_TOKEN;
        const headers = {
          'Authorization': `token ${token}`,
          'Accept': 'application/vnd.github.v3+json'
        };
        const repos = [
          'HOSTSERVERDOBRASIL/XDB-PAINELBACK-V2',
          'HOSTSERVERDOBRASIL/XDB-PAINELFRONT-V2'
        ];
        async function getCommitCount(repo) {
          const response = await fetch(`https://api.github.com/repos/${repo}/commits?author=bkhenrique`, { headers });
          const commits = await response.json();
          return commits.length;
        }
        async function countAllCommits() {
          let totalCommits = 0;
          for (const repo of repos) {
            const count = await getCommitCount(repo);
            totalCommits += count;
          }
          return totalCommits;
        }
        countAllCommits().then(totalCommits => {
          const readmePath = './README.md';
          const readmeContent = fs.readFileSync(readmePath, 'utf-8');
          const updatedReadme = readmeContent.replace(
            /Total de Commits nos repositórios privados: \*\*\d+\*\*/,
            `Total de Commits nos repositórios privados: **${totalCommits}**`
          );
          fs.writeFileSync(readmePath, updatedReadme);
        });

    # Comitar as mudanças no README.md
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Updated README with total commits"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TO_TOKEN }}
