name: Update README with Commit Count

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # Fazer checkout do repositório
    - name: Check out the repository
      uses: actions/checkout@v2

    # Configurar Node.js para rodar o script
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Instalar dependências necessárias
    - name: Install dependencies
      run: npm install



    # Rodar o script JavaScript para contar commits e atualizar o README.md
    - name: Run update-readme.js
      run: node .github/workflows/update-readme.js

    # Mostrar o conteúdo do README.md para verificar mudanças
    - name: Show README content
      run: cat README.md

    # Comitar as mudanças no README.md
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit --allow-empty -m "Updated README with total commits"
        git push
    env:
      TO_TOKEN: ${{ secrets.TO_TOKEN }}

